### ISSUE TITLE
Add @here++

### ISSUE THREAD

**Issue by jcraigk** [jcraigk/kudochest#117]
Add an option to recognize `@here++`, which requires pinging the chat platform each time it occurs to find out who is online.

For Slack it will require 1+N synchronous API calls to make this happen, might not be feasible for large channels. If API limits hit, will need to be limited and replaced with an error messge "Sorry there are too many people in this channel to use @here".
https://api.slack.com/methods/conversations.members to get channel members
https://api.slack.com/methods/users.getPresence on each member to get presenence

Discord investigation TODO

**Comment by brand-it** [comment]
APPROVE 🥇
